## S14a: Lab 2 - Numpy

Below is quick quickstart with numpy, designed to give new users a sense of how the library works. There is so much more functionality, and developers have provided an incredible [tutorial](https://numpy.org/devdocs/user/quickstart.html) for anyone ready for a deeper dive.

Also for need X need guidance, take a look at the [reference](https://numpy.org/doc/1.18/reference/index.html).

### The basics: 1D and 2D arrays

In [5]:
# Import numpy

import numpy as np

In [6]:
# Build a one dimensional (1D) numpy array directly

numpy_1d = np.array([1, 2, 3])
numpy_1d

array([1, 2, 3])

In [7]:
# Take a look at 1D dimensionality

np.ndim(numpy_1d)

1

In [8]:
# Take a look at 1D shape - (length, 

np.shape(numpy_1d)

(3,)

In [9]:
# Grab values at certain positions in 1D

numpy_1d[0]

1

In [10]:
# Build a two dimensional (2D) numpy array - "array of arrays"

numpy_2d = np.array([[4, 5, 6], [7, 8, 9]])
numpy_2d

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
# Take a look at 2D dimensionality

np.ndim(numpy_2d)

2

In [12]:
# Take a look at a 2D shape - (#row, #col)

np.shape(numpy_2d)

(2, 3)

In [14]:
# !!!YOUR TURN!!!

# Grab a value at row 1, column 2 at certain positions in 2D
numpy_2d[0, 1]

5

In [15]:
# Slice out portions of the array

numpy_2d[1, 1:3]

array([8, 9])

In [16]:
# Grab with condition
numpy_2d[numpy_2d >= 6]

array([6, 7, 8, 9])

In [17]:
# Reshape your 3d array, reversing rows and cols

numpy_2d.reshape(3, 2)

array([[4, 5],
       [6, 7],
       [8, 9]])

In [33]:
# Or try to transpose

np.transpose(numpy_2d)

array([[4, 7],
       [5, 8],
       [6, 9]])

### Building / transforming arrays - selections

In [19]:
# Build a numpy array using a range - (start at, up to, step size)

np.arange(3, 10, 3)

array([3, 6, 9])

In [20]:
# Build a numpy array using evenly spaced points in a range - (start at, up to, breakpoints)

np.linspace(3, 15, 5)

array([ 3.,  6.,  9., 12., 15.])

In [21]:
# Create 1D array of 0s

np.zeros(3)

array([0., 0., 0.])

In [22]:
# Create 2D array of 1s

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# !!!YOUR TURN!!!

# Create 2D array (3, 3) of random numbers
# Docs: https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random
randC = np.random.random((3,3))

In [41]:
# Get min and max
[randC.min(), randC.max()]

[0.07180298354910608, 0.957952386342698]

### Math, [ref.](https://numpy.org/doc/1.18/reference/routines.math.html)

In [42]:
# Addition / subtraction (you can define type)

npx = np.array([[1, 2], [3, 4]], dtype=np.float64)
npy = np.array([[5, 6], [7, 8]], dtype=np.float64)

print('+.', np.add(npx, npy))
print('-.', np.subtract(npx, npy))

+. [[ 6.  8.]
 [10. 12.]]
-. [[-4. -4.]
 [-4. -4.]]


In [43]:
# Multiplication / divide

print('Multiply:\n', np.multiply(npx, npy))
print('Divide:\n', np.divide(npx, npy))


Multiply:
 [[ 5. 12.]
 [21. 32.]]
Divide:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [44]:
# And other nice Math functions

print(np.sqrt(npx))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [50]:
# !!!YOUR TURN!!!

# Look at the documentation for the `sum` method:
# https://numpy.org/doc/stable/reference/generated/numpy.sum.html
# Pay attention to the second argument, the axis
# try to sum the npx array vertically and horizontally
print("col", np.sum(npx, axis= 0))
print("row", np.sum(npx, axis = 1))

col [4. 6.]
row [3. 7.]


In [29]:
# Broadcasting - when performing mathematical operations, shape matters

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(len(x)):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [30]:
# Check out this multiplication example

# First let's multiply a (4, 3) array by a (3, 1) vector - there are two ways to do this
print('Multiplication of matrix and vector:')
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 11, 12])
print(f'Check shapes: {np.shape(matrix)} X {np.shape(vector)}\n', )

prod1 = np.multiply(matrix, vector)
print(f'Scalar multiplication {np.shape(prod1)}:')
print(prod1, '\n')
prod2 = np.matmul(matrix, vector)
print(f'Matrix multiplication {np.shape(prod2)}:')
print(prod2)

Multiplication of matrix and vector:
Check shapes: (3, 3) X (3,)

Scalar multiplication (3, 3):
[[ 10  22  36]
 [ 40  55  72]
 [ 70  88 108]] 

Matrix multiplication (3,):
[ 68 167 266]


In [31]:
# Copying - if you need your changes not to effect the original array, make a copy
y_copy = y.copy()
y_copy[0][0:] = -9999
print(y)
print(y_copy)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[-9999 -9999 -9999]
 [    5     5     7]
 [    8     8    10]
 [   11    11    13]]


In [29]:
# Try to discover a numpy method not mentioned here, and share what you find.